config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'projects#index'

  resources :projects
  resources :notes

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


        if user.has_role? :admin
            can :manage, :all
        else
            can :read, :all
        end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :attachment_one, :styles => { 
				:medium => "600x600>", 
				:thumb => "100x100>"
				 },

				 :default_url => "/images/:style/missing.png"

	validates_attachment_content_type :attachment_one,  
									  :content_type => /\Aimage\/.*\Z/
									  

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  	
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :user_name
    # devise_parameter_sanitizer.for(:sign_in) << :user_name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def new
		@notes = Note.new
	end	


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to projects_path
    else
      logger.debug("Project creation failed")
      flash[:alert] = "Project creation failed #{@project.errors.full_messages.join('')}"
      redirect_to new_projects_path
    end
  end

  def index
    @projects = current_user.projects
    @new_project = Project.new
  end

  def show
    @project = Project.find(params[:id])

  end

  def edit
    @project = Project.find(params[:id])
  end 

  def update
    @project = Project.find(params[:id])
      @project.update_attributes(project_params)
     
    redirect_to projects_path
  end 

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to :controller => 'projects', :action => 'index'
    end

   

  private

  def project_params
    params.require(:project).permit(:title, :description, :materials, :attachment_one)
  end
end	

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end
	
end		

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<a href="projects#create">Create a new Project</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DIY</title>
  <link rel="stylesheet" type="text/css" href="/css/styles.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <body>
    <div id="wrapper">
      <div id="navBar">
        <div id="logo">My DIY!</div>

        <nav>
          <ul>
            <li><%= link_to "Home", projects_path(@project), class: 'link' %></li>
            <li><%= render "shared/login_actions" %></li>
          </ul>
        </nav>
      </div>

      <br/>
      <br/>
      <br/>


<div id="content">
<%= yield %>
</div>

</body>

	   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>



</body>
</html>

app/views/projects/create.html.erb
<h1>Error to the face!</h1>

<% if @project.errors.full_messages.any? %>
<ul>
	<% @project.errors.full_messages.each do |error| %>
	<li><%= error %></li>
	<br />
	<% end %>
</ul>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit your project</h1>

<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description%>
  <%= f.text_field :description %>

  <%= f.label :materials%>
  <%= f.text_field :materials %>

  <%= f.submit :update %>
<% end %>

app/views/projects/index.html.erb
<br />


<% @projects.each do |project| %>


<% @project = project %>
<div id= "project">
<%= image_tag @project.attachment_one.url(:thumb) %>
<br />
<div id="project-title"><%= link_to @project.title, project_path(@project), class: 'link' %></div>
<br />
<%= link_to "Edit Project", edit_project_path(@project), class: 'link' %>
<br />

<%= button_to 'Delete Project', project, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %>
</div>

<% end %>


<br />
<br />
<br />

<a href="projects/new"><h1>Create a new Project</h1></a>

app/views/projects/new.html.erb
<%= form_for(@project) do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
	<br>
  <%= f.label :description, "Description" %>
  <%= f.text_field :description %>
	<br />
  <%= f.label :materials, "Materials" %>
  <%= f.text_field :materials %>
	<br />

  <%= f.submit "Submit" %>
<% end %>

app/views/projects/show.html.erb
<%= render 'shared/project' %>

<br />
<br />
<br />

<%= image_tag @project.attachment_one.url(:medium) %>

<%= form_for @project, :url => project_path, :html => { :multipart => true } do |form| %>

  <%= form.file_field :attachment_one %>

  <%= form.submit "Create" %>

<% end %>

app/views/shared/_login_actions.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/shared/_project.html.erb
<div class="project">

<div class="project-title"><%= @project.title %></div>

<br />
<h3>About This Project</h3>
<br />

<div class="project-description"><%= @project.description %></div>

<br />
<h3>Materials used</h3>
<br />

<div class="project-materials"><%= @project.materials %></div>


</div>